### ISSUE TITLE
dgm create android

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#11]
While running:

```
dgm create android MyApp --url=http://www.example.com
```

The following "warnings" were output:

```
Created Cordova project.
Downloaded DrupalGap development kit.
Extracted DrupalGap development kit.
Initialized DrupalGap settings.js file.
Updated site_path in settings.js.
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
mkdir: path already exists: /home/tyler/Desktop/phonegap-code/MyApp/www
cp: dest file already exists: /home/tyler/Desktop/phonegap-code/MyAppMyApp/www/index.html
```

The warnings about the `mkdir` and `cp` commands seem strange. I then `cd` into the MyApp directory, and try to run:

```
cordova build
```

That results in this error though:

```
/usr/local/lib/node_modules/cordova/src/util.js:57
            throw new Error('Current working directory is not a Cordova-based 
                  ^
Error: Current working directory is not a Cordova-based project.
    at Object.module.exports.cdProjectRoot (/usr/local/lib/node_modules/cordova/src/util.js:57:19)
    at CLI.build (/usr/local/lib/node_modules/cordova/src/build.js:25:36)
    at new CLI (/usr/local/lib/node_modules/cordova/src/cli.js:101:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/bin/cordova:41:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Any thoughts on this?

**Comment by signalpoint** [comment]
Ok, so I ran an update to get the latest cordova:

```
npm update -g cordova
```

That says I'm now running 3.5.0-0.2.7, I then run this command again:

```
dgm create android MyApp --url=http://www.example.com
```

Which provides this output:

```
Created Cordova project.
Removed default www directory.
Downloaded DrupalGap development kit.
Extracted DrupalGap development kit.
Initialized DrupalGap settings.js file.
Updated site_path in settings.js.
npm http GET https://registry.npmjs.org/cordova-android/3.6.3
npm http 200 https://registry.npmjs.org/cordova-android/3.6.3
Unable to fetch platform android: Error: EACCES, mkdir '/home/tyler/tmp/npm-3599-pGrzfWKa'
Unable to fetch platform android: Error: EACCES, mkdir '/home/tyler/tmp/npm-3599-pGrzfWKa'
Unable to fetch platform android: Error: EACCES, mkdir '/home/tyler/tmp/npm-3599-pGrzfWKa'
Unable to fetch platform android: Error: EACCES, mkdir '/home/tyler/tmp/npm-3599-pGrzfWKa'
Unable to fetch platform android: Error: EACCES, mkdir '/home/tyler/tmp/npm-3599-pGrzfWKa'
npm http GET https://registry.npmjs.org/org.apache.cordova.console
npm http 404 https://registry.npmjs.org/org.apache.cordova.console
404 Not Found: org.apache.cordova.console
404 Not Found: org.apache.cordova.console
404 Not Found: org.apache.cordova.console
404 Not Found: org.apache.cordova.console
404 Not Found: org.apache.cordova.console
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
No platforms added to this project. Please use `cordova platform add <platform>`.
```

Switch into the newly created directory, and running `cordova build` results in the same error about "Current working directory is not a Cordova-based project."

**Comment by alexschedrov** [comment]
Yes, I know about this issue. I want fix it asap. Unfortunately something was changed on the cordova side.

**Comment by signalpoint** [comment]
@Sanchiz Alrighty, thanks for the quick response!

**Comment by signalpoint** [comment]
@Sanchiz FYI, I just run another update, now I'm running cordova 4.0.0 and then running:

```
sudo dgm create android MyApp --url=http://www.example.com
```

That got me a bit further, in that the `mkdir` commands were executed properly. But this error still persists:

```
No platforms added to this project. Please use `cordova platform add <platform>`.
```

Thank you again for your continued efforts!

**Comment by alexschedrov** [comment]
Nice catch. I just updated cordova to 4.0.0 and some weird bugs are gone.

Also for the Android platform id "com.example" is required parameter, that's the main problem here.

**Comment by alexschedrov** [comment]
But `cordova create` says "At least the dir must be provided to create new project. See cordova help" :)

**Comment by alexschedrov** [comment]
hm, maybe I'm wrong. Anyway I will work on this.

**Comment by alexschedrov** [comment]
@signalpoint, can you try it again? It works for me when I added ANDROID_HOME variable to my path.

```
export ANDROID_HOME=`brew --prefix android`
```

in `~/.bashrc`

**Comment by signalpoint** [comment]
@Sanchiz Yes, it now works, thank you.

I believe it was my fault for not having the most up to date Android SDK earlier. Now that it is updated, and I have the proper PATH settings, it works, thanks!
